// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadTrace returns the embedded CollectionSpec for trace.
func loadTrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load trace: %w", err)
	}

	return spec, err
}

// loadTraceObjects loads trace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*traceObjects
//	*tracePrograms
//	*traceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// traceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceSpecs struct {
	traceProgramSpecs
	traceMapSpecs
	traceVariableSpecs
}

// traceProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceProgramSpecs struct {
	FentryExecve             *ebpf.ProgramSpec `ebpf:"fentry_execve"`
	HandleExecveRawTpNonCore *ebpf.ProgramSpec `ebpf:"handle_execve_raw_tp_non_core"`
	HandleExecveTpNonCore    *ebpf.ProgramSpec `ebpf:"handle_execve_tp_non_core"`
	KprobeExecveNonCore      *ebpf.ProgramSpec `ebpf:"kprobe_execve_non_core"`
}

// traceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceMapSpecs struct {
}

// traceVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceVariableSpecs struct {
}

// traceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceObjects struct {
	tracePrograms
	traceMaps
	traceVariables
}

func (o *traceObjects) Close() error {
	return _TraceClose(
		&o.tracePrograms,
		&o.traceMaps,
	)
}

// traceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceMaps struct {
}

func (m *traceMaps) Close() error {
	return _TraceClose()
}

// traceVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceVariables struct {
}

// tracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracePrograms struct {
	FentryExecve             *ebpf.Program `ebpf:"fentry_execve"`
	HandleExecveRawTpNonCore *ebpf.Program `ebpf:"handle_execve_raw_tp_non_core"`
	HandleExecveTpNonCore    *ebpf.Program `ebpf:"handle_execve_tp_non_core"`
	KprobeExecveNonCore      *ebpf.Program `ebpf:"kprobe_execve_non_core"`
}

func (p *tracePrograms) Close() error {
	return _TraceClose(
		p.FentryExecve,
		p.HandleExecveRawTpNonCore,
		p.HandleExecveTpNonCore,
		p.KprobeExecveNonCore,
	)
}

func _TraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed trace_x86_bpfel.o
var _TraceBytes []byte
